# Generated by Django 5.2.6 on 2025-12-01 01:41

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0005_alter_doctor_canthoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='hora_ingreso',
            field=models.DateField(default=timezone.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
