# Generated by Django 5.2.6 on 2025-12-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0007_cliente_alter_empleado_foto_alter_empleado_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
