# Generated by Django 5.2.6 on 2025-12-01 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0009_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxApp.cliente', verbose_name='Cliente'),
        ),
    ]
