# Generated by Django 5.2.6 on 2025-12-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0010_alter_pedido_cliente'),
    ]

    operations = [
    ]
