# Generated by Django 5.2.6 on 2025-12-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0011_auto_20251201_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
