# Generated by Django 5.2.6 on 2025-12-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0012_remove_pedido_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='Precio Unitario')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxApp.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del Pedido',
                'verbose_name_plural': 'Productos del Pedido',
                'db_table': 'pedido',
            },
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
