# Generated by Django 5.2.6 on 2025-12-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0013_alter_pedido_table_pedidoproducto_delete_pedidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='PedidoProducto',
            table='pedidoProducto',
        ),
    ]
