# Generated by Django 5.2.6 on 2025-12-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0014_alter_pedidoproducto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoProducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidoProducto',
            name='pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='boxApp.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoProducto',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='boxApp.producto', verbose_name='Producto'),
        ),
    ]
