# Generated by Django 5.2.6 on 2025-12-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0015_alter_pedidoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
